### ISSUE TITLE
Planned Features (ROADMAP)

### ISSUE THREAD

**Issue by olets** [olets/zsh-test-runner#2]
Check the [branch:next ROADMAP.md](https://github.com/olets/zsh-test-runner/blob/next/ROADMAP.md) to see what work is underway or planned.

Planned features are listed as comments below. You can vote for something by giving it a thumbs up.

👉 New features should not be proposed here. Create a new Issue

This is a side project. If you _really_ want a feature you're welcome to donate. Email me, we can set up https://issuehunt.io/ or something.

**Comment by olets** [comment]
Functions automatically run with every test

> currently "next up"

-   [ ] `ZTR_SETUP_FN` is a user-definable function
-   [ ] `ZTR_TEARDOWN_FN` is a user-definable function
-   [ ] `ztr test` runs `ZTR_SETUP_FN` before `eval`ing the input
-   [ ] `ztr test` runs `ZTR_TEARDOWN_FN` after `eval`ing the input

**Comment by olets** [comment]
Functions manually run with every set of tests

> currently "up second"

-   [ ] `ZTR_BOOTSTRAP_FN` is a user-definable function
-   [ ] `ztr bootstrap` runs the bootstrap function
-   [ ] `ZTR_CLEAN_FN` is a user-definable function
-   [ ] `ztr clean` runs the clean function
-   [ ] `ztr reset` is a shorthand for `ztr clean && ztr clear`

**Comment by olets** [comment]
Queue

> currently "up third"

-   [ ] `ztr queue <cmd> [<notes>]` queues a command for later testing
-   [ ] `ztr run-queue [(--quiet | -q)] [--summary]` runs all queued commands
    -   [ ] `(--quiet | -q)` behaves as in `ztr test`
    -   [ ] `--summary` runs `ztr summary` after the last queued command
    -   [ ] regardless of whether or not `--summary` is passed, exit code is `$ZTR_COUNT_FAIL`
